# Generated by Django 4.1.2 on 2023-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrainTumorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.CharField(max_length=100)),
                ("p_name", models.CharField(max_length=100)),
                ("p_email", models.EmailField(max_length=100)),
                ("p_image", models.ImageField(null=True, upload_to="posts")),
            ],
        ),
        migrations.CreateModel(
            name="ChestDiseaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.CharField(max_length=100)),
                ("p_name", models.CharField(max_length=100)),
                ("p_email", models.EmailField(max_length=100)),
                ("p_image", models.ImageField(null=True, upload_to="posts")),
            ],
        ),
        migrations.CreateModel(
            name="KidneyDiseaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.CharField(max_length=100)),
                ("p_name", models.CharField(max_length=100)),
                ("p_email", models.EmailField(max_length=100)),
                ("p_image", models.ImageField(null=True, upload_to="posts")),
            ],
        ),
        migrations.CreateModel(
            name="SkinDiseaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_id", models.CharField(max_length=100)),
                ("p_name", models.CharField(max_length=100)),
                ("p_email", models.EmailField(max_length=100)),
                ("p_image", models.ImageField(null=True, upload_to="posts")),
            ],
        ),
    ]
