# Generated by Django 4.1.2 on 2023-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease_detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="braintumormodel",
            name="p_disease",
            field=models.CharField(default="Not determined", max_length=100),
        ),
        migrations.AddField(
            model_name="chestdiseasemodel",
            name="p_disease",
            field=models.CharField(default="Not determined", max_length=100),
        ),
        migrations.AddField(
            model_name="kidneydiseasemodel",
            name="p_disease",
            field=models.CharField(default="Not determined", max_length=100),
        ),
        migrations.AddField(
            model_name="skindiseasemodel",
            name="p_disease",
            field=models.CharField(default="Not determined", max_length=100),
        ),
    ]
